"""Description of changesd

Revision ID: 5e0fb205e043
Revises: 
Create Date: 2024-04-01 01:59:31.586603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e0fb205e043'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_id',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='RUB', nullable=False),
    sa.Column('card_1', sa.Float(), server_default='0', nullable=False),
    sa.Column('name_card_1', sa.String(length=50), nullable=True),
    sa.Column('cash', sa.Float(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id_id'), 'user_id', ['id'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), server_default='0', nullable=False),
    sa.Column('card_number', sa.Integer(), nullable=False),
    sa.Column('is_cash', sa.Boolean(), server_default='False', nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user_id.id'], ),
    sa.PrimaryKeyConstraint('id', 'card_number')
    )
    op.create_table('task',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('task', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user_id.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_user_id_id'), table_name='user_id')
    op.drop_table('user_id')
    # ### end Alembic commands ###
